site_name: SARA II - Rural Indicators
theme:
  name: material
  language: en

repo_url: https://github.com/urbanoeliecer/Sara00 

extra_css: 
  - styles/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
nav:
  - Index: index.md
  - Principal Panel : principal.md
  - Ind. de Correlación de Ejec,: admin/indCorelEjec.md
  - Ind. de Interv. General: admin/indInterGnrl.md
  - Inf. de Proyectos por JAC (MVC): admin/infPryMVC.md
  - Inf. de Activ. por Proy. (MVC): admin/infActivMesPryMVC.md
  - Inf. de Infraestructura: admin/infElem.md
  - Back:
    - Conexión: back/conexion.md
    - Estilos: back/estilos.md
  - Definición:
    - Entorno: tecnico/entorno.md
    - Estructura BD: tecnico/bdest.md
    - Requerimientos: tecnico/req.md
    - Roles: tecnico/roles.md