site_name: SARA II - Rural Indicators
theme:
  name: material
  language: en

repo_url: https://github.com/urbanoeliecer/Sara00 

extra_css: 
  - styles/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
nav:
  - Index: index.md
  - Principal Panel : principal.md
  - Correlational Intervention Indicator: admin/indCorelEjec.md
  - Overall Intervention Indicator: admin/indInterGnrl.md
  - Municipal Intervention Report (MVC: admin/infPryMVC.md
  - Monthly Activ. by Project Report (MVC): admin/infActivMesPryMVC.md
  - Infrastructure by JAC Report: admin/infElem.md
  - Back:
    - Conection: back/conexion.md
    - Styles: back/estilos.md
  - Definici√≥n:
    - BD structure: tecnico/bdest.md
    - Code: tecnico/entorno.md
    - Profiles: tecnico/roles.md
    - Requeriments: tecnico/req.md
