site_name: SARA II - Rural Indicators
theme:
  name: material
  language: es

repo_url: https://github.com/urbanoeliecer/Sara00 

extra_css: 
  - styles/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
nav:
  - Inicio: index.md
  - Revisión de Sesión: loginRev.md
  - Panel Principal: principal.md
  - Ind. de Correlación de Ejec,: admin/indCorelEjec.md
  - Ind. de Interv. Cons. (MVC): admin/indInterConsMVC.md
  - Ind. de Interv. General: admin/indInterGnrl.md
  - Inf. de Elementos: admin/infElem.md
  - Inf. de Activ. por Proy. (MVC): admin/infActivMesPryMVC.md
  - Back:
    - Conexión: back/conexion.md
    - Estilos: back/estilos.md
  - Definición:
    - Entorno: tecnico/entorno.md
    - Estructura: tecnico/bdEst.md
    - Requerimientos: tecnico/req.md
    - Roles: tecnico/roles.md